name: Delete Old Workflows

on:
  workflow_call:
  workflow_dispatch:
#  schedule:
#    - cron: 0 18 * * *

jobs:
  Cleaning:
    runs-on: ubuntu-24.04

    steps:
    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 10
        keep_minimum_runs: 30

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 100
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
